# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 王立杰的博客
email: ttyard@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  记录和总结工作/生活中的知识储备.并把这些经验分享出来,希望能够帮你踏过一些坑。内容涉及云计算、网络技术、开发、JAVA、Python、系统运维、自动化运维与监控
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
rss_url: /pages/atom.xml

# 作者信息
author: 
  name: wanglijie
  email: ttyard@gmail.com
  link: http://www.wanglijie.cn
  weibo: http://weibo.com/wljie
  github: http://github.com/ttyard
  music:
  linkedin: https://www.linkedin.com/
  
# google analytics 设置
ga:
  id: UA-91628081-1
  url: www.wanglijie.cn

# disqus 设置
disqus:
  shortname: wljcn

# 主题设置，自动激活某个标签
active: 运维

# 首页除了最新文章外显示分类
cates: 
  - 运维
  - 云计算

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

# gavatar头像及Favicon
gavatar: http://images.wanglijie.cn/public/img/logo.png
favicon: http://images.wanglijie.cn/public/img/favicon.ico
  
  
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
